# Generated by Django 3.1.3 on 2021-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0002_datafragment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafragment',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
